name: build_docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/superpower-institute/setup_wrf

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.IMAGE }}"
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}
      - name: Build image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          labels: setup_wrf:latest
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/setup_wrf.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: setup_wrf
          path: /tmp/setup_wrf.tar

  test:
    runs-on: ubuntu-latest

    needs: [build]

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: setup_wrf
          path: /tmp
      - name: Load image into docker context
        run: |
          docker load --input /tmp/setup_wrf.tar
      - name: Cache Geog data
        id: cache-geog
        uses: actions/cache@v4
        with:
          path: data/geog
          key: ${{ runner.os }}
      - name: Download and extract geography data
        if: steps.cache-geog.outputs.cache-hit != 'true'
        run: |
          mkdir -p data/geog
          curl "https://www2.mmm.ucar.edu/wrf/src/wps_files/geog_low_res_mandatory.tar.gz" -o data/geog/geog_low_res_mandatory.tar.gz
          tar -xvzf data/geog/geog_low_res_mandatory.tar.gz -C data/geog
      - name: Run test
        run: |
          docker run --rm -v $(PWD):/project -v $(PWD)/data/geog/WPS_GEOG:/opt/wrf/geog setup_wrf python setup_for_wrf.py -c config.docker.json
